-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kauppayhtyma CASCADE;
DROP TABLE IF EXISTS Kauppa CASCADE;
DROP TABLE IF EXISTS Tuote CASCADE;
DROP TABLE IF EXISTS Ostotapahtuma CASCADE;